FORMAT: 1A

# Product Manager - Assessment

Product manager is a simple API, managing products
    and hierarchical categories of products

## Products Collection [/products]

### List All Products [GET]

+ Response 200 (application/json)

        [
            
        ]

### Create a New Product [POST]

You may create your own product using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                
            }